language: perl
perl:
    - "5.19"
    - "5.18"
install:
    - cpanm -q --notest Dist::Zilla
    - dzil authordeps --missing | cpanm -q --notest
    - dzil listdeps --author --missing | cpanm -q --notest
script:
    - dzil test --all
